### ISSUE TITLE
The stream links don't work

### ISSUE THREAD

**Issue by Tdotsown** [dwbfox/kodi-ethiopian-tv#6]
I have the links if you want.

**Comment by dwbfox** [comment]
It looks like EBS has transitioned to a paid service, which may explain why the service went down so abruptly. I'm a bit hesitant to put non-public streams especially now that they're actually charging users money for it. What I might consider is to simply allow an interactive option to allow the user to supply their own streaming links. 

This issue is a duplicate of #4
